### PR TITLE
#221 Support Package

### LINKED ISSUE #221: Support packages
Mirror of #86

### PR DESCRIPTION
**Pull request by Dufgui**
Fixes #221 

Changes proposed in this Pull Request:
  - Add parsing element inside package

This doesn't parse package itself, neitheir add package info on entity

### CODE REVIEW

**Comment by MathieuAA** [comment]
It looks good... but I've a few doubts:
  - `::getXmlElementFromRawIndexes` is just syntaxic sugar for `root.packagedElement[rawObjects.rawXXXIndexes[i]]`, and adds more complexity in the extracted method,
  - `::getXmlElementFromRawIndexes` isn't tested,
  - there are no tests for objects other than classes (it looks like it works though),
  - and I don't get the need for `var indexInfo = {index: i, path: path};`.

**Comment by Dufgui** [comment]
- Yes it's just to avoid code duplication
- your are right, i will add test soon
- Yes too, so i will add relation and enum
- as before i have just the index, but now i need the path (packageElement path) to get the parent of the node element, in order to parse it after founding all element to parse.

**Comment by Dufgui** [comment]
So here is all the unit tests. Is it ok ?

**Comment by MathieuAA** [comment]
I'll need time to review it all. I'll try to do it during the week-end.

**Comment by Dufgui** [comment]
thanks ;o).

**Comment by MathieuAA** [comment]
After a quick review:
  - I've added some comments,
  - I get the need for `indexInfo` so big 👍,
  - I've you tried with a lot of packages? Like 10+, or even more (a hundred for instance)? I'd be curious to find out whether too deep a recursion would make Node crash -> that would introduce a need for a better algorithm or a upper-bound value,
  - Have you tried with cross-objects? For instance, say that you have 3 classes A, B and C. A is in no package, B in its package and C in a two-level deep package. What if I want to have a relationship (or more) between them? Or if B is an enum and is used in A and C? I know it's pretty unlikely to have these cases but I'd like to be 100% sure about this. Some users actually love to give you incredibly strange cases...

**Comment by Dufgui** [comment]
- ok

- ok

- So it's not so complicated, it's in 2 phases:

1. Get the index of each element with his path. We just navigate threw the tree. It's mandatory to get all element. Yes it's recursive but it's not so complex. A ten level package produce ten level of call. I looking for max stack size info in nodejs? I found a understable (for me) on SO : "default stack size is 492 kBytes (32-bit) and 984 kBytes (64-bit)." because I don't know what contains this stack (method name, param, context, etc....). So I think a have a large gap before having a problem with recurse no ? And the recurse is directly link to the recursion 1 by 1 so it's a o(n) algorythm.
2. Simple loop to go threw the xml tree to go to the parent package of current parsed element. So it's a simple o(n). For this one, I think we can create a cache for large package structure. But I think we can have a large number of class, lesser a large number of package....

- Yes
 I tested it, and it's in the unit test. You can look the Xmi, each time I create 3 classes (1 in a package, 1 in no package,  and one in 2 level of package),, relation between 2 of them. 1 enum inside a package. So it's unitary tested for the 3 parser (modelio, genmymodel, umldesigner).

**Comment by MathieuAA** [comment]
Indeed, but I've seen diagrams with a lot of packages and a lot more of classes. That's a considerable amount of data to keep in memory and node doesn't (yet?) make use the Tail Call Optimization unless you have the harmony flag and use strict mode. I'll try some things tomorrow.

**Comment by Dufgui** [comment]
In fact I not copy Xml entity. I just manipulate path to entity. So I hope it's ok in memory.
Tail call optim is an exchange from stack to memory usage. So I choose memory keep safe because i don't think we have more then 1000 level of embedeed package for exemple. See my code a do comment on it, if you see something wich need to change

**Comment by Dufgui** [comment]
any news?

**Comment by MathieuAA** [comment]
Yes! I've played with the code a bit and it worked great. Just one more test to pass... and some things to fix (comments in the code).

**Comment by MathieuAA** [comment]
I'll merge this PR this week-end :) Thanks a lot!

**Pull request merged**
