### PR TITLE
user defined primitive type and typed association

### PR DESCRIPTION
**Pull request by kpallardy**
Fixes # .

Changes proposed in this Pull Request:
- manage user defined primitive type like LocalDate
- convert field to association when the type is a user defined class

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'll test it sometime this week to confirm an issue... can you explain what the problem is exactly? So as to be sure I don't make any mistakes.

**Comment by kpallardy** [comment]
I define a field with type of another class (instead of association). But when the `entitiescreator.setFieldsOfEntity()` resolve it, he check only primitive type and enum class (not entity class). So no fieldType attribute is added in json file and I retrieve a exception later.

**Comment by MathieuAA** [comment]
It shouldn't be done this way. The whole point of using the UML format is to be as precise as possible. Thus, in this case, relationships should be used. If some UML tools propose to type a field after another class (and not a primitive type), then they are faulty.

**Comment by MathieuAA** [comment]
It shouldn't be done at all, if I get it right. The point is to use relationships.

Le 24 octobre 2016 12:11:21 GMT+02:00, kpallardy <notifications@github.com> a écrit :
>I define a field with type of another class (instead of association).
>But when the `entitiescreator.setFieldsOfEntity()` resolve it, he check
>only primitive type and enum class (not entity class). So no fieldType
>attribute is added in json file and I retrieve a exception later.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/pull/216#issuecomment-255701062

-- 
Mathieu ABOU-AICHI

**Pull request closed without merging**
