### PR TITLE
fix wrong required side and add required check on many to many

### PR DESCRIPTION
**Pull request by Dufgui**
Changes proposed in this Pull Request:
  - fix wrong required side (on UML designer) and add required check on many to many

Be carrefull, this change is after 
fix memberEnd order in association for umlDesigner #230

Is base on a master with this one, in case of problems i can rebase on master after

### CODE REVIEW

**Comment by Dufgui** [comment]
I will rebase it to have a cleaner patch

**Comment by MathieuAA** [comment]
Ok! By the way, I've noticed you didn't supply an email address in your GitHub profile, it may be useful so that I can speak more easily about this project with you ;)

**Comment by Dufgui** [comment]
i add it...

**Comment by Dufgui** [comment]
I close this PR due to wrong rebase strategy and reopen a clear one

**Pull request closed without merging**
