### PR TITLE
fix memberEnd order in association for umlDesigner

### PR DESCRIPTION
**Pull request by Dufgui**
Changes proposed in this Pull Request:
  - fix memberEnd usage because we cannot change the order of element in xml with the UI, but we can change the member end attribute. So we must use this information.

### CODE REVIEW

**Comment by MathieuAA** [comment]
I don't see the need to do that.

**Comment by Dufgui** [comment]
Step to reproduce :

1. Create 2 entities : A  & B , link them with a many to one bidirectionnal. 
2. Launch juml, you see an error, you must change the owner side of your relation
3. You can change the owner side by changing the order in the ownerEnd (without delete and recreate the association). Because It's a source of error, to remove and recreate association instead of just change the order as the UI let you.

**Comment by MathieuAA** [comment]
Thanks, I'll test everything the day after tomorrow =)

**Comment by Dufgui** [comment]
any news?

**Comment by MathieuAA** [comment]
Do you have an XMI so that I can test your PR?

**Comment by Dufgui** [comment]
Not now but in few days yes. I am on holidays

**Comment by MathieuAA** [comment]
Enjoy them! 

Le 11 novembre 2016 14:17:03 GMT+01:00, Duff <notifications@github.com> a écrit :
>Not now but in few days yes. I am on holidays
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/pull/230#issuecomment-259955163

-- 
Mathieu ABOU-AICHI

**Comment by Dufgui** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="20131001" xmlns:xmi="http://www.omg.org/spec/XMI/20131001" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML" xmi:id="_i3w8wKvuEeakNc8DUbvWFw" name="NewModel">
  <packagedElement xmi:type="uml:Class" xmi:id="_qsVsUKvuEeakNc8DUbvWFw" name="A"/>
  <packagedElement xmi:type="uml:Class" xmi:id="_r0Ia0KvuEeakNc8DUbvWFw" name="B"/>
  <packagedElement xmi:type="uml:Association" xmi:id="_zgzyoKvuEeakNc8DUbvWFw" name="A_as_bs" memberEnd="_zgzypKvuEeakNc8DUbvWFw _zgzyoavuEeakNc8DUbvWFw" navigableOwnedEnd="_zgzypKvuEeakNc8DUbvWFw _zgzyoavuEeakNc8DUbvWFw">
    <ownedEnd xmi:id="_zgzyoavuEeakNc8DUbvWFw" name="bs" type="_r0Ia0KvuEeakNc8DUbvWFw" association="_zgzyoKvuEeakNc8DUbvWFw">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_zgzyoqvuEeakNc8DUbvWFw"/>
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_zgzyo6vuEeakNc8DUbvWFw" value="*"/>
    </ownedEnd>
    <ownedEnd xmi:id="_zgzypKvuEeakNc8DUbvWFw" name="as" type="_qsVsUKvuEeakNc8DUbvWFw" association="_zgzyoKvuEeakNc8DUbvWFw">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_zgzypavuEeakNc8DUbvWFw" value="1"/>
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_zgzypqvuEeakNc8DUbvWFw" value="1"/>
    </ownedEnd>
  </packagedElement>
</uml:Model>
```

**Comment by MathieuAA** [comment]
Thanks, I'll check everything tomorrow evening.

**Comment by MathieuAA** [comment]
I'd rather not make choices for the user. If, however, this could be made as a choice to fix the diagram then an `--auto-fix` option could be made...

**Comment by Dufgui** [comment]
ok i will work on it, when i have time

**Comment by MathieuAA** [comment]
There's a project about that. I'll ask that you have some rights.

Le 18 novembre 2016 10:59:02 GMT+01:00, Duff <notifications@github.com> a écrit :
>ok i will work on it, when i have time
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/pull/230#issuecomment-261492973

-- 
Mathieu ABOU-AICHI

**Comment by Dufgui** [comment]
use the #237

**Pull request closed without merging**
